export const mockProductCategories = [
  { label: "Beverages", value: "beverages" },
  { label: "Bakery", value: "bakery" },
  { label: "Personal Care", value: "personal-care" },
  { label: "Household", value: "household" },
] as const;

export const mockProducts = [
  {
    pId: "P001001",
    barcode: "8850001001001",
    name: "Drinking Water 600ml",
    description: "Purified drinking water in a 600ml bottle.",
    sellingPrice: 10,
    costPrice: 6,
    category: "Beverages",
    categoryValue: "beverages",
    minStockHq: 100,
    minStockBranch: 24,
    status: "active",
  },
  {
    pId: "P001002",
    barcode: "8850001002008",
    name: "Coke 325ml",
    description: "Carbonated cola drink in a 325ml can.",
    sellingPrice: 18,
    costPrice: 12,
    category: "Beverages",
    categoryValue: "beverages",
    minStockHq: 120,
    minStockBranch: 36,
    status: "active",
  },
  {
    pId: "P002015",
    barcode: "8850002015007",
    name: "Milk Bread",
    description: "Soft sliced milk bread.",
    sellingPrice: 35,
    costPrice: 22,
    category: "Snacks & Bakery",
    categoryValue: "bakery",
    minStockHq: 50,
    minStockBranch: 12,
    status: "active",
  },
  {
    pId: "P003020",
    barcode: "8850003020000",
    name: "Cooling Shampoo",
    description: "Cooling shampoo for daily hair care.",
    sellingPrice: 129,
    costPrice: 82,
    category: "Personal Care",
    categoryValue: "personal-care",
    minStockHq: 30,
    minStockBranch: 8,
    status: "active",
  },
  {
    pId: "P004010",
    barcode: "8850004010000",
    name: "Bar Soap 90g",
    description: "Everyday cleansing bar soap.",
    sellingPrice: 29,
    costPrice: 17,
    category: "Household",
    categoryValue: "household",
    minStockHq: 60,
    minStockBranch: 15,
    status: "active",
  },
  {
    pId: "P005011",
    barcode: "8850005011006",
    name: "Green Tea 500ml",
    description: "Ready-to-drink green tea.",
    sellingPrice: 25,
    costPrice: 16,
    category: "Beverages",
    categoryValue: "beverages",
    minStockHq: 80,
    minStockBranch: 20,
    status: "active",
  },
  {
    pId: "P006012",
    barcode: "8850006012002",
    name: "Butter Croissant",
    description: "Flaky croissant made with butter.",
    sellingPrice: 45,
    costPrice: 28,
    category: "Snacks & Bakery",
    categoryValue: "bakery",
    minStockHq: 40,
    minStockBranch: 10,
    status: "active",
  },
  {
    pId: "P007013",
    barcode: "8850007013008",
    name: "Toothpaste 150g",
    description: "Fluoride toothpaste for daily use.",
    sellingPrice: 89,
    costPrice: 55,
    category: "Personal Care",
    categoryValue: "personal-care",
    minStockHq: 35,
    minStockBranch: 10,
    status: "active",
  },
  {
    pId: "P008014",
    barcode: "8850008014004",
    name: "Laundry Detergent",
    description: "Concentrated liquid laundry detergent.",
    sellingPrice: 159,
    costPrice: 105,
    category: "Household",
    categoryValue: "household",
    minStockHq: 25,
    minStockBranch: 6,
    status: "active",
  },
  {
    pId: "P009015",
    barcode: "8850009015000",
    name: "Orange Juice 1L",
    description: "Orange juice in a one-liter bottle.",
    sellingPrice: 65,
    costPrice: 41,
    category: "Beverages",
    categoryValue: "beverages",
    minStockHq: 45,
    minStockBranch: 12,
    status: "active",
  },
] as const;

export type MockProduct = (typeof mockProducts)[number];
