export const mockProductCategories = [
  { label: "Beverages", value: "beverages" },
  { label: "Bakery", value: "bakery" },
  { label: "Personal Care", value: "personal-care" },
  { label: "Household", value: "household" },
] as const;

export const mockProducts = [
  {
    pId: "P001001",
    name: "Drinking Water 600ml",
    sellingPrice: 10,
    category: "Beverages",
    categoryValue: "beverages",
    status: "active",
  },
  {
    pId: "P001002",
    name: "Coke 325ml",
    sellingPrice: 18,
    category: "Beverages",
    categoryValue: "beverages",
    status: "active",
  },
  {
    pId: "P002015",
    name: "Milk Bread",
    sellingPrice: 35,
    category: "Snacks & Bakery",
    categoryValue: "bakery",
    status: "active",
  },
  {
    pId: "P003020",
    name: "Cooling Shampoo",
    sellingPrice: 129,
    category: "Personal Care",
    categoryValue: "personal-care",
    status: "active",
  },
  {
    pId: "P004010",
    name: "Bar Soap 90g",
    sellingPrice: 29,
    category: "Household",
    categoryValue: "household",
    status: "active",
  },
  {
    pId: "P005011",
    name: "Green Tea 500ml",
    sellingPrice: 25,
    category: "Beverages",
    categoryValue: "beverages",
    status: "active",
  },
  {
    pId: "P006012",
    name: "Butter Croissant",
    sellingPrice: 45,
    category: "Snacks & Bakery",
    categoryValue: "bakery",
    status: "active",
  },
  {
    pId: "P007013",
    name: "Toothpaste 150g",
    sellingPrice: 89,
    category: "Personal Care",
    categoryValue: "personal-care",
    status: "active",
  },
  {
    pId: "P008014",
    name: "Laundry Detergent",
    sellingPrice: 159,
    category: "Household",
    categoryValue: "household",
    status: "active",
  },
  {
    pId: "P009015",
    name: "Orange Juice 1L",
    sellingPrice: 65,
    category: "Beverages",
    categoryValue: "beverages",
    status: "active",
  },
] as const;
